{
 "title": "Podman",
 "description": "Podman仪表盘，由冰雪殇璃陌梦基于Prometheus-podman-exporter制作",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "宿主机",
    "query": {
     "query": "label_values(podman_container_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "容器总览",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "podman_container_info", "legendFormat": "基本信息" },
    { "expr": "podman_container_state", "legendFormat": "状态" },
    {
     "expr": "podman_container_mem_usage_bytes",
     "legendFormat": "__auto"
    },
    { "expr": "podman_container_exit_code", "legendFormat": "__auto" },
    {
     "expr": "time() - podman_container_started_seconds",
     "legendFormat": "__auto"
    },
    { "expr": "podman_container_pids", "legendFormat": "__auto" },
    {
     "expr": "podman_container_mem_usage_bytes / (podman_container_mem_limit_bytes + 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "podman_container_net_input_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "容器详情（宿主机：$instance）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "容器总CPU占比",
   "type": "gauge",
   "description": "相对于宿主机的CPU核数",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(podman_container_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval])) / count(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(podman_container_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval]) / 60",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "podman_container_mem_usage_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{id}}_current"
    },
    {
     "expr": "podman_container_mem_limit_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{id}}_max"
    }
   ]
  },
  {
   "title": "容器总内存占比",
   "type": "gauge",
   "description": "相对于宿主机的内存",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_container_mem_usage_bytes{instance=~\"$instance\"}) / sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "磁盘",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(podman_container_block_input_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{id}}_in"
    },
    {
     "expr": "increase(podman_container_block_output_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{id}}_out"
    }
   ]
  },
  {
   "title": "网络",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "increase(podman_container_net_input_total{instance=\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "{{id}}_in"
    },
    {
     "expr": "increase(podman_container_net_output_total{instance=\"$instance\"}[$__rate_interval]) * 8",
     "legendFormat": "{{id}}_out"
    }
   ]
  },
  { "title": "镜像信息（宿主机：$instance）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "镜像总大小",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_image_size{instance=~\"$instance\"})",
     "legendFormat": "占用的存储空间"
    }
   ]
  },
  {
   "title": "磁盘占比",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podman_image_size{instance=~\"$instance\"}) / sum(node_filesystem_size_bytes{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "镜像信息",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "podman_image_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "podman_image_created_seconds{instance=\"$instance\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "podman_image_size{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}